# Generated by Django 4.2.7 on 2023-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.IntegerField(default=''),
        ),
    ]
